<?php

/*
 |--------------------------------------------------------------------------
 | DO NOT EDIT THIS FILE DIRECTLY.
 |--------------------------------------------------------------------------
 | This file reads from your .env configuration file and should not
 | be modified directly.
*/

// This is used by the mysql dump options in spatie backup
$dump_options = [
    'dump_binary_path' => env('DB_DUMP_PATH', '/usr/local/bin'),  // only the path, so without 'mysqldump'
    'timeout' => 60 * 5, // 5 minute timeout
    // 'exclude_tables' => ['table1', 'table2'],
    // 'add_extra_option' => '--optionname=optionvalue',
];

// Default to false (preserves original behavior for non-RDS installs).
// Set DB_DUMP_SINGLE_TRANSACTION=true in .env for RDS or other environments
// that require --single-transaction (e.g. no LOCK TABLES privilege).
$dump_options['use_single_transaction'] = (env('DB_DUMP_SINGLE_TRANSACTION', 'false') === 'true');

// Opt-in flag for skipping SSL on the dump connection. Only add the key when
// it's true - spatie's processExtraDumpParameters has a bug where a `false`
// value routes through callMethodOnDumper's `if (!$methodValue)` branch, which
// calls setSkipSsl() with no args, and that setter defaults to true. So an
// explicit false would silently become true. When opted in, spatie emits the
// correct per-DBMS flag: --ssl-mode=DISABLED for MySQL 8.4+, --skip-ssl for
// older MySQL and MariaDB. Do NOT set this via add_extra_option; that route
// ships the raw flag as-is and mariadb-dump rejects ssl-mode.
if (env('DB_DUMP_SKIP_SSL') === 'true') {
    $dump_options['skip_ssl'] = true;
}

// PDO SSL options for the app database connection. Each entry is only added
// when its env var is actually set - passing PDO::MYSQL_ATTR_SSL_* options
// with a null value is NOT the same as omitting them. libmysql / libmariadb
// tries to negotiate SSL against a null spec and the connect fails with
// "Cannot connect to MySQL using SSL".
// This shape also lets a user legitimately configure CA-only SSL by
// leaving KEY / CERT unset without breaking the client-cert branch below.
$ssl_options = [];
if (env('DB_SSL')) {
    if (env('DB_SSL_IS_PAAS')) {
        // Managed cloud DB flow (RDS, Azure Database, Cloud SQL): server CA
        // only, no client cert.
        if (env('DB_SSL_CA_PATH') !== null) {
            $ssl_options[PDO::MYSQL_ATTR_SSL_CA] = env('DB_SSL_CA_PATH');
        }
        $ssl_options[PDO::MYSQL_ATTR_SSL_VERIFY_SERVER_CERT] = (bool) env('DB_SSL_VERIFY_SERVER', false);
    } else {
        // Self-hosted flow: full mutual TLS with client key / cert.
        if (env('DB_SSL_KEY_PATH') !== null) {
            $ssl_options[PDO::MYSQL_ATTR_SSL_KEY] = env('DB_SSL_KEY_PATH');
        }
        if (env('DB_SSL_CERT_PATH') !== null) {
            $ssl_options[PDO::MYSQL_ATTR_SSL_CERT] = env('DB_SSL_CERT_PATH');
        }
        if (env('DB_SSL_CA_PATH') !== null) {
            $ssl_options[PDO::MYSQL_ATTR_SSL_CA] = env('DB_SSL_CA_PATH');
        }
        if (env('DB_SSL_CIPHER') !== null) {
            $ssl_options[PDO::MYSQL_ATTR_SSL_CIPHER] = env('DB_SSL_CIPHER');
        }
        $ssl_options[PDO::MYSQL_ATTR_SSL_VERIFY_SERVER_CERT] = (bool) env('DB_SSL_VERIFY_SERVER', false);
    }
}

return [

    /*
    |--------------------------------------------------------------------------
    | PDO Fetch Style
    |--------------------------------------------------------------------------
    |
    | By default, database results will be returned as instances of the PHP
    | stdClass object; however, you may desire to retrieve records in an
    | array format for simplicity. Here you can tweak the fetch style.
    |
    */

    'fetch' => PDO::FETCH_CLASS,

    /*
    |--------------------------------------------------------------------------
    | Default Database Connection Name
    |--------------------------------------------------------------------------
    |
    | Here you may specify which of the database connections below you wish
    | to use as your default connection for all database work. Of course
    | you may use many connections at once using the Database library.
    |
    */

    'default' => env('DB_CONNECTION', 'mysql'),

    /*
    |--------------------------------------------------------------------------
    | Database Connections
    |--------------------------------------------------------------------------
    |
    | Here are each of the database connections setup for your application.
    | Of course, examples of configuring each database platform that is
    | supported by Laravel is shown below to make development simple.
    |
    |
    | All database work in Laravel is done through the PHP PDO facilities
    | so make sure you have the driver for your particular database of
    | choice installed on your machine before you begin development.
    |
    */

    'connections' => [

        'sqlite' => [
            'driver' => 'sqlite',
            'database' => database_path('database.sqlite'),
            'prefix' => '',
        ],

        'sqlite_testing' => [
            'driver' => 'sqlite',
            'database' => ':memory:',
            'prefix' => '',
        ],

        'mysql' => [
            'driver' => 'mysql',
            'host' => env('DB_HOST', 'localhost'),
            'port' => (int) env('DB_PORT', 3306),
            'database' => env('DB_DATABASE', 'forge'),
            'username' => env('DB_USERNAME', 'forge'),
            'password' => env('DB_PASSWORD', ''),
            'charset' => env('DB_CHARSET', 'utf8mb4'),
            'collation' => env('DB_COLLATION', 'utf8mb4_unicode_ci'),
            'prefix' => env('DB_PREFIX', null),
            'strict' => false,
            'engine' => 'InnoDB',
            'unix_socket' => env('DB_SOCKET', ''),
            'dump' => $dump_options,
            'dump_command_timeout' => 60 * 5, // 5 minute timeout
            'dump_using_single_transaction' => true, // perform dump using a single transaction
            'options' => $ssl_options,
        ],

        // Use this connection (DB_CONNECTION=mariadb) when the server is
        // MariaDB. Spatie's backup picks the MariaDb dumper for this driver,
        // which invokes mariadb-dump instead of the deprecated mysqldump
        // symlink and uses --skip-ssl instead of --ssl-mode=DISABLED.
        'mariadb' => [
            'driver' => 'mariadb',
            'host' => env('DB_HOST', 'localhost'),
            'port' => (int) env('DB_PORT', 3306),
            'database' => env('DB_DATABASE', 'forge'),
            'username' => env('DB_USERNAME', 'forge'),
            'password' => env('DB_PASSWORD', ''),
            'charset' => env('DB_CHARSET', 'utf8mb4'),
            'collation' => env('DB_COLLATION', 'utf8mb4_unicode_ci'),
            'prefix' => env('DB_PREFIX', null),
            'strict' => false,
            'engine' => 'InnoDB',
            'unix_socket' => env('DB_SOCKET', ''),
            'dump' => $dump_options,
            'dump_command_timeout' => 60 * 5,
            'dump_using_single_transaction' => true,
            'options' => $ssl_options,
        ],

        'pgsql' => [
            'driver' => 'pgsql',
            'host' => env('DB_HOST', 'localhost'),
            'port' => env('DB_PORT', '5432'),
            'database' => env('DB_DATABASE', 'forge'),
            'username' => env('DB_USERNAME', 'forge'),
            'password' => env('DB_PASSWORD', ''),
            'charset' => 'utf8',
            'prefix' => '',
            'schema' => 'public',
        ],

        'sqlsrv' => [
            'driver' => 'sqlsrv',
            'host' => env('DB_HOST', 'localhost'),
            'database' => env('DB_DATABASE', 'forge'),
            'username' => env('DB_USERNAME', 'forge'),
            'password' => env('DB_PASSWORD', ''),
            'charset' => 'utf8',
            'prefix' => '',
        ],

    ],

    /*
    |--------------------------------------------------------------------------
    | Migration Repository Table
    |--------------------------------------------------------------------------
    |
    | This table keeps track of all the migrations that have already run for
    | your application. Using this information, we can determine which of
    | the migrations on disk haven't actually been run in the database.
    |
    */

    'migrations' => 'migrations',

    /*
    |--------------------------------------------------------------------------
    | Redis Databases
    |--------------------------------------------------------------------------
    |
    | Redis is an open source, fast, and advanced key-value store that also
    | provides a richer set of commands than a typical key-value systems
    | such as APC or Memcached. Laravel makes it easy to dig right in.
    |
    */

    'redis' => [

        'cluster' => false,

        'default' => [
            'host' => env('REDIS_HOST', 'localhost'),
            'password' => env('REDIS_PASSWORD', null),
            'port' => env('REDIS_PORT', 6379),
            'database' => env('REDIS_DATABASE', 0),
        ],

    ],

];
